// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avocdhvgtmkguyboohkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2b2NkaHZndG1rZ3V5Ym9vaGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTE2OTgsImV4cCI6MjA1OTEyNzY5OH0.NFACJYAVVyruWhBhddzj9R6qN6vC-ILr7McohWoD6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);